apiVersion: v1
kind: Template
metadata:
  name: passwordpusher
  annotations:
    openshift.io/display-name: "Passwordpusher"
    description: "Securely communicate passwords over the web"
    iconClass: "icon-rails"
    tags: "utility"
parameters:
- name: PASSWORDPUSHER_IMAGE
  description: select the passwordpusher image
  value: docker.io/pglombardo/pwpush-openshift
  required: true
labels:
  template: passwordpusher
  app: passwordpusher


objects:

- apiVersion: v1
  kind: Service
  metadata:
    name: passwordpusher
    labels:
      app: passwordpusher
  spec:
    selector:
      app: passwordpusher
    ports:
    - name: passwordpusher-service
      port: 443
      protocol: TCP
      targetPort: 5000


- apiVersion: v1
  kind: Route
  metadata:
    name: passwordpusher
    labels:
      app: passwordpusher
  spec:
    to:
      name: passwordpusher

- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    name: passwordpusher
    labels:
      app: passwordpusher
  spec:
    replicas: 1
    strategy:
      type: Rolling
    template:
      metadata:
        labels:
          app: passwordpusher
      spec:
        containers:
        - name: passwordpusher
          image: ${PASSWORDPUSHER_IMAGE}
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
                - touch
                - /tmp/health
            initialDelaySeconds: 15
            timeoutSeconds: 1
          readinessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 15
            timeoutSeconds: 1
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 500m
              memory: 2Gi
        restartPolicy: Always
