base: &base
  adapter: sqlite3
  timeout: 5000

development:
  database: #{shared_path}/db/development.sqlite3
  <<: *base

test:
  database: #{shared_path}/db/test.sqlite3
  <<: *base

private:
  database: #{shared_path}/db/private.sqlite3
  <<: *base

production:
  database: #{shared_path}/db/production.sqlite3
  <<: *base
